classdef config_mwm < base_config
    % config_mwm Global constants
    properties(Constant)
        RESULTS_DIR = 'results/mwm';
        
        TRIALS_PER_SESSION = 4;
        SESSIONS = 3;
        TRIALS = config_mwm.TRIALS_PER_SESSION*config_mwm.SESSIONS;        
        TRIAL_TIMEOUT = 90; % seconds
        GROUPS = 2;
        
        % centre point of arena in cm        
        CENTRE_X = 0;
        CENTRE_Y = 0;
        % radius of the arena
        ARENA_R = 100;
        % platform position and radius
        PLATFORM_X = -50;
        PLATFORM_Y = 10;
        PLATFORM_R = 6;        
        
        TRAJECTORY_DATA_DIRS = {... % 1st set
            '/home/tiago/neuroscience/rat_navigation/data/set1/', ...                                      
            '/home/tiago/neuroscience/rat_navigation/data/set2/', ...
            '/home/tiago/neuroscience/rat_navigation/data/set3/', ...
        }; 
    
    	% used to calibrate the trajectories
        TRAJECTORY_SNAPSHOTS_DIRS = {...
            '/home/tiago/neuroscience/rat_navigation/screenshots/set1/', ...
            '/home/tiago/neuroscience/rat_navigation/screenshots/set2/', ...
            '/home/tiago/neuroscience/rat_navigation/screenshots/set3/' ...
        };        
    
        % number of animals to discard from each group
        REGULARIZE_GROUPS = 1;
        NDISCARD = 0;
        DISCARD_FEATURE = features.AVERAGE_SPEED;
    
        % relation between animal ids and groups (1 = control, 2 = stress,
        % 3 = control + modified diet, 4 = stress + modified diet                
        TRAJECTORY_GROUPS = {...
                 %1st set   
                [87, 1; 91, 1; 93, 1; 95, 1; 99, 1; 101, 1; 103, 1; ...
                 114, 1; 115, 1; 121, 1; 88, 2; 90, 2; 98, 2; 100, 2; ...  
                 104, 2; 106, 2; 108, 2; 113, 2; 118, 2; 122, 2], ...
                 % 2nd set
                [43, 1; 49, 1; 52, 1; 57, 1; 59, 1; 65, 1; 75, 1; ...
                 82, 1; 44, 2; 50, 2; 53, 2; 58, 2; 60, 2; 67, 2; ...
                 71, 2; 76, 2; 78, 2; 83, 2], ...
                 % 3rd set
                [50, 1; 61, 1; 67, 1; 71, 1; 75, 1; 83, 1; 90, 1; ...
                 94, 1; 100, 1; 111, 1; 52, 2; 57, 2; 63, 2; 69, 2; ...
                 73, 2; 81, 2; 92, 2; 96, 2; 102, 2; 107, 2; 51, 3; ...
                 55, 3; 56, 3; 62, 3; 68, 3; 74, 3; 82, 3; 91, 3; 95, 3; ...
                 106, 3; 53, 4; 58, 4; 64, 4; 72, 4; 76, 4; 84, 4; 97, 4; ...
                 103, 4; 108, 4; 113, 4] ...
         };                      
               
%         REDUCED_BEHAVIOURAL_CLASSES = [ ...
%             tag.combine_tags( [config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'TT')), config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'IC'))]), ...
%             config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'FS')), ...
%             config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'SC')), ...
%             config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'SS')), ...
%             config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'CR')), ...
%             tag.combine_tags( [config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'SO')), config_mwm.TAGS(tag.tag_position(config_mwm.TAGS, 'ST'))])  ...                          
%         ];
%                                      
        CLUSTER_CLASS_MINIMUM_SAMPLES_P = 0.01; % 2% o
        CLUSTER_CLASS_MINIMUM_SAMPLES_EXP = 0.75;
        
        DEFAULT_SEGMENT_LENGTH = 250;
        DEFAULT_SEGMENT_OVERLAP = 0.90;        
        DEFAULT_NUMBER_OF_CLUSTERS = 120;
                
        DEFAULT_FEATURE_SET = [features.MEDIAN_RADIUS, features.IQR_RADIUS, features.FOCUS, features.CENTRE_DISPLACEMENT, ...
                               features.CV_INNER_RADIUS, features.PLATFORM_SURROUNDINGS, features.BOUNDARY_ECCENTRICITY, features.LONGEST_LOOP]; 
                                                                   
        %%
        %% Tags sets - number/indices have to match the list below        
        %%
        TAGS_FULL = 1; 
        TAGS250_90 = 2; % Important: go from "more detailed" to less detailed 
        TAGS250_70 = 3;
        TAGS300_70 = 4;
        
        TAGS_CONFIG = { ... % values are: file that stores the tags, segment length, overlap, default number of clusters
            { '/home/tiago/neuroscience/rat_navigation/trajectories/labels_full.csv', 0, 0, 0}, ...
            { '/home/tiago/neuroscience/rat_navigation/trajectories/segment_labels_250c.csv', 250, 0.90, 75}, ... 
            { '/home/tiago/neuroscience/rat_navigation/trajectories/segment_labels_250_70.csv', 250, 0.70, 35}, ...
            { '/home/tiago/neuroscience/rat_navigation/trajectories/segment_labels_300_70.csv', 300, 0.70, 37}, ...            
        };
                
        OUTPUT_DIR = '/home/tiago/results/'; % where to put all the graphics and other generated output
        CLASSES_COLORMAP = @jet;
    end 
    
    methods    
        function inst = config_mwm()
            inst@base_config('Morris water maze', ...                
               [ tag('TT', 'thigmotaxis', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 1), ... % default tags
                 tag('IC', 'incursion', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 2), ...
                 tag('SS', 'scanning-surroundings', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 7), ...                 
                 tag('SC', 'scanning', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 3), ...
                 tag('FS', 'focused search', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 4), ...                                  
                 tag('SO', 'self orienting', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 6), ...
                 tag('CR', 'chaining response', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 5), ...
                 tag('ST', 'target scanning', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 8), ...
                 tag('TS', 'target sweep', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 3), ...             
                 tag('DF', 'direct finding', base_config.TAG_TYPE_BEHAVIOUR_CLASS), ...
                 tag('AT', 'approaching_target', base_config.TAG_TYPE_BEHAVIOUR_CLASS), ...                              
                 tag('CI', 'circling', base_config.TAG_TYPE_BEHAVIOUR_CLASS, 8), ...                                   
                 tag('CP', 'close pass', base_config.TAG_TYPE_TRAJECTORY_ATTRIBUTE), ...
                 tag('S1', 'selected 1', base_config.TAG_TYPE_TRAJECTORY_ATTRIBUTE) ], ...
               [] ...% no additional data representation
            );   
        end
                
        % Imports trajectories from Noldus data file's
        function traj = load_data(inst)
            addpath(fullfile(fileparts(mfilename('fullpath')),'../import/noldus'));
            traj = load_trajectories(1:3, 1);
        end        
    end
end

